parent: classic
name: joyeria
display_name: Tema para la joyería
version: 1.0.0
author:
  name: "Ignacio farre"
  email: "iganciofarrefuentes@gmail.com"
  url: "http://www.ignaciofarre.com"

assets:
  # If you're using this theme as child and you want to load
  # the parent theme assets, uncomment this line.
  use_parent_assets: true


# The following lines are showing how to load assets in your page
  # Uncomment and change value to start loading css or js files
#  css:
#    all:
#      - id: custom-lib-style
#        path: assets/css/custom-lib.css
#    product:
#      - id: product-style
#        path: assets/css/product.css
#        media: all
#        priority: 200
#  js:
#    cart:
#      - id: cat-extra-lib
#        path: assets/js/cart-lib.js